#!/bin/bash
#
#PSEUDOCÓDIGO
#
#read $task
#read $reminder
#si se deja en blanco, no hay recordatorio
#si se pone la hora, queda seteado para hoy y a esa hora
#si se pone día y hora:
#convert $reminder hh:mm  dd:mm into dd month at hhmm
#esto creo que con cut -df basta
#$task_#=$(wc -l list.txt + 1) 
#$task_# + " " + $task + " "  $reminder" >> list.txt
echo
echo "¿Qué tarea tienes pendiente?"
read task; echo
echo "¿Quieres añadir un recordatorio? el formato para hacerlo es hh:mm dd/mm"
read reminder

echo "$task $reminder" >> list.txt; echo
echo "Has añadido la tarea con éxito :)"
echo "Tienes $(wc -l list.txt) pendiente/s"; echo
